apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: djangoBook
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: djangoBook
      app.kubernetes.io/component: backend
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: djangoBook
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: djangoBook
        image: worldwidemaster/sample_django_docker
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
